---

- hosts: localhost
  become: true
  tasks:

# Add various repos and keys for Google Chrome, VScode, and Bitwarden
  - name: Import the Google Chrome GPG key
    rpm_key:
      state: present
      key: https://dl.google.com/linux/linux_signing_key.pub

  - name: Add the Google Chrome repository
    yum_repository:
      name: google-chrome
      description: Google Chrome
      baseurl: https://dl.google.com/linux/chrome/rpm/stable/$basearch
      gpgcheck: yes
      gpgkey: https://dl.google.com/linux/linux_signing_key.pub
      enabled: yes

  - name: Import the Microsoft GPG key
    rpm_key:
      state: present
      key: https://packages.microsoft.com/keys/microsoft.asc

  - name: Add the Visual Studio Code repository
    yum_repository:
      name: vscode
      description: Visual Studio Code
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: yes
      gpgcheck: yes
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc

  - name: Import the Bitwarden GPG key
    rpm_key:
      state: present
      key: https://sisheogorath.github.io/bitwarden-rpm-deb-mirror/pub.gpg

  - name: Add the Bitwarden repository
    yum_repository:
      name: bitwarden
      description: Bitwarden
      baseurl: https://sisheogorath.github.io/bitwarden-rpm-deb-mirror/rpms
      enabled: yes
      gpgcheck: yes
      gpgkey: https://sisheogorath.github.io/bitwarden-rpm-deb-mirror/pub.gpg

# Add RPM Fusion for non-free stuff
  - name: Install RPM Fusion free and non-free
    dnf:
      name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm,https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
      state: present
    when: ansible_facts['os_family'] == 'Fedora'

# Update the system
  - name: DNF Update
    dnf:
      name: "*"
      state: latest

# Install Desktop and Apps
  - name: Install Gnome and Applications
    dnf:
      state: latest
      name:
        - avahi
        - acpid
        - cups
        - cups-browsed
        - gnome-shell
        - gnome-terminal
        - gnome-tweaks
        - gnome-packagekit
        - gnome-software
        - gnome-system-monitor
        - gnome-disk-utility
        - gnome-extensions-app
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-blur-my-shell
        - gnome-shell-extension-user-theme
        - papirus-icon-theme
        - jetbrains-mono-fonts-all
        - nautilus
        - gvfs-nfs
        - nfs-utils
        - timeshift
        - plymouth
        - plymouth-system-theme
        - plymouth-theme-spinfinity
        - libreoffice
        - gedit
        - rsync
        - oh-my-posh
        - borgbackup
        - firefox
        - google-chrome-stable
        - bitwarden
        - code
        - tailscale

# Stop and Start services        
  - name: Disable SSHD
    ansible.builtin.systemd.service:
      name: sshd
      enabled: false

  - name: Enable Tailscale
    ansible.builtin.systemd.service:
      name: tailscaled
      enabled: true

  - name: Enable Cups
    ansible.builtin.systemd.service:
      name: cups
      enabled: true

  - name: Enable avahi-daemon
    ansible.builtin.systemd.service:
      name: avahi-daemon
      enabled: true

  - name: Enable acpid
    ansible.builtin.systemd.service:
      name: acpid
      enabled: true
  
  - name: Disable default
    ansible.builtin.systemd_service:
      name: default.target
      enabled: false

  - name: Enable desktop
    ansible.builtin.systemd_service:
      name: graphical.target
      enabled: true
