# Install ansible and ansible core 
- name: Install Plasma Desktop
  hosts: localhost
  become: true
  tasks:
    - name: System Update 
      community.general.pacman:
         update_cache: true
         upgrade: true

    - name: Plasma Desktop
      community.general.pacman:
        name:
          - btrfs-progs
          - xfsprogs
          - plasma-desktop
          - xorg-server
          - xorg-xwayland
          - sddm
          - sddm-kcm
          - kscreen
          - avahi
          - bluez
          - bluedevil
          - plasma-wayland-protocols
          - firewalld
          - plasma-firewall
          - plasma-nm
          - plasma-pa
          - kde-gtk-config
          - breeze-gtk
          - papirus-icon-theme
          - ark
          - konsole
          - dolphin
          - plasma-systemmonitor
          - kinfocenter
          - discover
          - networkmanager
          - acpi
          - acpid
          - cups
          - cups-browsed
          - cronie
          - syslog-ng
          - nfs-utils
          - xdg-user-dirs
          - xdg-desktop-portal
          - xdg-desktop-portal-kde
          - xdg-desktop-portal-gtk
          - plymouth
          - openssh
          - fwupd
          - reflector
          - git
          - rsync
          - borg
          - flatpak
        state: present

    - name: Add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpaks
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - com.google.Chrome
          - com.spotify.Client
          - org.kde.kalk
          - org.kde.kwrite
          - com.github.tchx84.Flatseal
          - com.bitwarden.desktop
          - com.visualstudio.code
          - org.libreoffice.LibreOffice
          - com.discordapp.Discord

    - name: Start Cups
      ansible.builtin.systemd_service:
        enabled: true
        name: cups

    - name: Start Cronie
      ansible.builtin.systemd_service:
        enabled: true
        name: cronie

    - name: Start Fstrim
      ansible.builtin.systemd_service:
        enabled: true
        name: fstrim.timer

    - name: Start Bluetooth
      ansible.builtin.systemd_service:
        enabled: true
        name: bluetooth

    - name: Start FirewallD
      ansible.builtin.systemd_service:
        enabled: true
        name: firewalld

    - name: Start Acpid    
      ansible.builtin.systemd_service:
        enabled: true
        name: acpid

    - name: Start Avahi-Daemon    
      ansible.builtin.systemd_service:
        enabled: true
        name: avahi-daemon

    - name: Start SDDM    
      ansible.builtin.systemd_service:
        enabled: true
        name: sddm
