- name: Install KDE Plasma Desktop 
  hosts: localhost
  become: true
  tasks:
    - name: System Update 
      ansible.builtin.dnf:
         name: "*"
         state: latest
         
    - name: Add Tailscale repo
      ansible.builtin.yum_repository:
        name: tailscale
        description: tailscale repo
        baseurl: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        
    - name: Install Plasma Desktop
      ansible.builtin.dnf:
        name:
          - acpi
          - acpid
          - rsync
          - fwupd
          - flatpak
          - borgbackup
          - nfs-utils
          - cups
          - cups-browsed
          - avahi
          - plymouth
          - plymouth-system-theme
          - plymouth-theme-breeze
          - plymouth-theme-spinner
          - plymouth-theme-spinfinity
          - firewalld
          - NetworkManager
          - plasma-desktop
          - xorg-x11-server-Xwayland
          - NetworkManager-wifi
          - NetworkManager-bluetooth
          - kscreen
          - kinfocenter
          - sddm
          - sddm-kcm
          - sddm-themes
          - sddm-breeze
          - sddm-wayland-plasma
          - plasma-wayland-protocols
          - plasma-firewall
          - plasma-nm
          - plasma-pa
          - kde-gtk-config
          - konsole
          - dolphin
          - ark
          - vlc
          - plasma-systemmonitor
          - plasma-discover
          - plasma-discover-packagekit
          - xdg-user-dirs
          - xdg-desktop-portal
          - xdg-desktop-portal-kde
          - papirus-icon-theme
          - papirus-icon-theme-dark
          - papirus-icon-theme-light
          - tailscale
        state: present

    - name: Add the flathub flatpak repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpaks
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - app.zen_browser.zen
          - com.google.Chrome
          - org.kde.kwrite
          - org.kde.kcalc
          - org.kde.gwenview
          - com.bitwarden.desktop
          - com.visualstudio.code
          - org.libreoffice.LibreOffice
          - com.discordapp.Discord

    - name: Start Cups
      ansible.builtin.systemd_service:
        enabled: true
        name: cups
        
    - name: Start Tailscale
      ansible.builtin.systemd_service:
        enabled: true
        name: tailscaled

    - name: Start Acpid    
      ansible.builtin.systemd_service:
        enabled: true
        name: acpid

    - name: Start Avahi-Daemon    
      ansible.builtin.systemd_service:
        enabled: true
        name: avahi-daemon

    - name: Start SDDM    
      ansible.builtin.systemd_service:
        enabled: true
        name: sddm

    - name: Change default target to graphical.target
      ansible.builtin.file:
        src: /usr/lib/systemd/system/graphical.target
        dest: /etc/systemd/system/default.target
        state: link
